# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'  # Define una única imagen de agente

variables:
  dockerRegistryServiceConnection: '26f92ee5-dc77-4b9a-8fda-12eac25c74f6'
  imageRepository: 'alkituwebapp'
  containerRegistry: 'alkituwebapp.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

steps:
  # Paso 1: Compilar la imagen Docker
  - task: Docker@2
    displayName: Build Docker image
    inputs:
      command: build
      repository: $(imageRepository)
      dockerfile: $(dockerfilePath)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)

  # Paso 2: Subir la imagen al registro de contenedores
  - task: Docker@2
    displayName: Push Docker image
    inputs:
      command: push
      repository: $(imageRepository)
      containerRegistry: $(dockerRegistryServiceConnection)
      tags: |
        $(tag)
