version: '3.8'

services:
  development:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: development  # Use the 'development' stage from Dockerfile.prod for development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev

  production:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL="http://localhost:3000"
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    restart: unless-stopped
